const actions = {
  SET_STATE: 'builder/SET_STATE',
  INIT: 'builder/INIT',
  UPDATE_LAYOUTS: 'builder/UPDATE_LAYOUTS',
  ADD_WIDGET: 'builder/ADD_WIDGET',
  UPDATE_CURRENT_WIDGET: 'builder/UPDATE_CURRENT_WIDGET',
  COMMIT_WIDGET_CHANGES: 'builder/COMMIT_WIDGET_CHANGES',
  REMOVE_WIDGET: 'builder/REMOVE_WIDGET',
  OPEN_WIDGET_EDITOR: 'builder/OPEN_WIDGET_EDITOR',
  CLOSE_WIDGET_EDIOR: 'builder/CLOSE_WIDGET_EDITOR',
}

export default actions
